version: '3'
services:
  dosgato-admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      API_BASE: http://localhost
      RENDER_BASE: http://localhost:3002
      AUTH_REDIRECT: http://localhost:3001/login?clientId=dosgato-admin&returnUrl=http%3A%2F%2Flocalhost%3A3000%2Fadmin
    volumes:
      - ./src:/usr/app/src
      - ./static:/usr/app/static
      - ./svelte.config.js:/usr/app/svelte.config.js
      - ./vite.config.js:/usr/app/vite.config.js
  dosgato-api:
    build:
      context: ../dosgato
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 9229:9229
    environment:
      NODE_ENV: development
      TZ: America/Chicago
      MYSQL_USER: dosgato
      MYSQL_PASS: password
      MYSQL_DATABASE: dosgatodev
      MYSQL_HOST: mysql
      RESET_DB_ON_STARTUP: 'true'
      JWT_TRUSTED_ISSUERS: '[{ "iss": "unified-auth", "url": "http://fakeauth/jwks" }, { "iss": "dg-render", "secret": "rendertoken" }]'
    volumes:
      - ../dosgato/src:/usr/app/src
      - ../dosgato/testserver:/usr/app/testserver
    depends_on:
      - mysql
  dosgato-render:
    build:
      context: ../dosgato-render
    ports:
      - 3002:80
    environment:
      NODE_ENV: development
      DOSGATO_RENDER_JWT_SECRET: rendertoken
      DOSGATO_API_URL: http://dosgato-api/graphql
    volumes:
      - ../dosgato-render/src:/usr/app/src
      - ../dosgato-render/test:/usr/app/test
    depends_on:
      - dosgato-api
  fakeauth:
    image: registry.its.txstate.edu/unified-auth-stub:dev
    ports:
      - 3001:80
  mysql:
    image: percona:5
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dosgatodev
      MYSQL_USER: dosgato
      MYSQL_PASSWORD: password
    volumes:
      - dosgatodb:/var/lib/mysql
volumes:
  dosgatodb: {}
